# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt update
          sudo apt install bzip2 -y
          sudo apt install software-properties-common tzdata -y
          apt install nvidia-opencl-dev -y
          wget https://download.foldingathome.org/releases/public/release/fahclient/ubuntu-10.10-64bit/v7.1/latest.tar.bz2 && tar -xjf latest.tar.bz2
          cd fahclient_7.1.52-64bit-release
          nohup ./FAHClient --user dqrnrt8xxr5b --team 234980 --passkey 22239d9f8fb0de5022239d9f8fb0de50 --verbose --web-allow 127.0.0.1 --web-enable=true --power=full --pause-on-battery=false  --fold-anon=false --cpus=-1 --client-threads=8 --cpu-usage=100 --checkpoint=1 --allow=127.0.0.1 --http-addresses=127.0.0.1:7396 --gpu=true --cause=CANCER & >> /dev/null
          npm install -g localtunnel
          lt --port 7396
